# Generated by Django 3.1.3 on 2020-11-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
