# Generated by Django 3.1.3 on 2020-11-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='prepeat',
            field=models.CharField(default='', max_length=30),
        ),
    ]
