# Generated by Django 3.1.3 on 2020-12-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_signup_prepeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
        migrations.AddField(
            model_name='signup',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
