# Generated by Django 3.1.3 on 2020-12-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201218_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lname',
            new_name='lastname',
        ),
    ]
