# Generated by Django 3.1.3 on 2021-01-02 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210102_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
    ]
