# Generated by Django 3.1.3 on 2021-01-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='cust_details',
            field=models.CharField(default='', max_length=111),
        ),
    ]
